apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: rhobs-gateway
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: 98f89ac6b75d7e887090efdeb2778b132bd405b9
  name: rhobs-gateway
  namespace: rhobs-stage
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: h2c
    name: grpc-public
    port: 8090
    protocol: TCP
    targetPort: 8090
  - appProtocol: http
    name: internal
    port: 8081
    protocol: TCP
    targetPort: 8081
  - appProtocol: http
    name: public
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: rhobs-gateway
    app.kubernetes.io/part-of: rhobs
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
