apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosRuler
metadata:
  name: rhobs
  namespace: rhobs-int
spec:
  additionalArgs:
  - |-
    --tracing.config="config":
      "sampler_param": 2
      "sampler_type": "ratelimiting"
      "service_name": "thanos-ruler"
    "type": "JAEGER"
  additionalContainers:
  - args:
    - --reporter.grpc.host-port=dns:///otel-trace-writer-collector-headless.observatorium-tools.svc:14250
    - --reporter.type=grpc
    - --agent.tags=pod.namespace=$(NAMESPACE),pod.name=$(POD)
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    image: registry.redhat.io/rhosdt/jaeger-agent-rhel8:1.57.0-10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: 14271
        scheme: HTTP
      initialDelaySeconds: 1
    name: jaeger-agent
    ports:
    - containerPort: 5778
      name: configs
    - containerPort: 6831
      name: jaeger-thrift
    - containerPort: 14271
      name: metrics
    readinessProbe:
      httpGet:
        path: /
        port: 14271
        scheme: HTTP
      initialDelaySeconds: 1
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  alertLabelDrop:
  - rule_replica
  alertmanagerURL: dnssrv+http://alertmanager-cluster.rhobs-int.svc.cluster.local:9093
  baseImage: quay.io/redhat-services-prod/rhobs-mco-tenant/rhobs-thanos
  defaultObjectStorageConfig:
    key: thanos.yaml
    name: default-thanos-bucket
    optional: false
  evaluationInterval: 1m
  externalLabels:
    rule_replica: $(NAME)
  featureGates:
    serviceMonitor:
      enable: false
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  logLevel: info
  prometheusRuleSelector:
    matchLabels:
      operator.thanos.io/prometheus-rule: "true"
  queryLabelSelector:
    matchLabels:
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/query-api: "true"
  replicas: 1
  resourceRequirements:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  retention: 48h
  ruleConfigSelector:
    matchLabels:
      operator.thanos.io/rule-file: "true"
  ruleTenancyConfig:
    tenantLabel: tenant_id
    tenantValueLabel: operator.thanos.io/tenant
  storage:
    size: 10Gi
  version: 358a4a4341684ca1f199b6780891f4d09d5ca458
status: {}
